sbatch -o CB12-4F_adapter_trimming.out adapter_trimming.sh CB12-4F
sbatch -o CB78-3M_adapter_trimming.out adapter_trimming.sh CB78-3M
sbatch -o FMA22-2M_adapter_trimming.out adapter_trimming.sh FMA22-2M
sbatch -o FMA55-5M_adapter_trimming.out adapter_trimming.sh FMA55-5M
sbatch -o FMA88-5M_adapter_trimming.out adapter_trimming.sh FMA88-5M
sbatch -o FMB22-2M_adapter_trimming.out adapter_trimming.sh FMB22-2M
sbatch -o FMB66-2M_adapter_trimming.out adapter_trimming.sh FMB66-2M
sbatch -o L1A56-4F_adapter_trimming.out adapter_trimming.sh L1A56-4F
sbatch -o L1B12-1M_adapter_trimming.out adapter_trimming.sh L1B12-1M
sbatch -o L1B12-3F_adapter_trimming.out adapter_trimming.sh L1B12-3F
sbatch -o L2A34-5M_adapter_trimming.out adapter_trimming.sh L2A34-5M
sbatch -o L2B34-4M_adapter_trimming.out adapter_trimming.sh L2B34-4M
sbatch -o L3A23-5M_adapter_trimming.out adapter_trimming.sh L3A23-5M
sbatch -o L3A56-2F_adapter_trimming.out adapter_trimming.sh L3A56-2F
sbatch -o L3B24-5F_adapter_trimming.out adapter_trimming.sh L3B24-5F
sbatch -o L3B910-7M_adapter_trimming.out adapter_trimming.sh L3B910-7M
sbatch -o MFA22-1M_adapter_trimming.out adapter_trimming.sh MFA22-1M
sbatch -o MFA22-3F_adapter_trimming.out adapter_trimming.sh MFA22-3F
sbatch -o MFA88-4M_adapter_trimming.out adapter_trimming.sh MFA88-4M
sbatch -o MFA88-8F_adapter_trimming.out adapter_trimming.sh MFA88-8F
sbatch -o MFB22-8M_adapter_trimming.out adapter_trimming.sh MFB22-8M
sbatch -o MFB88-3M_adapter_trimming.out adapter_trimming.sh MFB88-3M
sbatch -o SAA23-5F_adapter_trimming.out adapter_trimming.sh SAA23-5F
sbatch -o SAB34-5M_adapter_trimming.out adapter_trimming.sh SAB34-5M
sbatch -o SAB57-2M_adapter_trimming.out adapter_trimming.sh SAB57-2M
