sbatch -o CB12-4F_merge_rrna_removal.out rrna_removal.sh CB12-4F_merge
sbatch -o CB78-3M_merge_rrna_removal.out rrna_removal.sh CB78-3M_merge
sbatch -o FMA22-2M_merge_rrna_removal.out rrna_removal.sh FMA22-2M_merge
sbatch -o FMA55-5M_merge_rrna_removal.out rrna_removal.sh FMA55-5M_merge
sbatch -o FMA88-5M_merge_rrna_removal.out rrna_removal.sh FMA88-5M_merge
sbatch -o FMB22-2M_merge_rrna_removal.out rrna_removal.sh FMB22-2M_merge
sbatch -o FMB66-2M_merge_rrna_removal.out rrna_removal.sh FMB66-2M_merge
sbatch -o L1A56-4F_merge_rrna_removal.out rrna_removal.sh L1A56-4F_merge
sbatch -o L1B12-1M_merge_rrna_removal.out rrna_removal.sh L1B12-1M_merge
sbatch -o L1B12-3F_merge_rrna_removal.out rrna_removal.sh L1B12-3F_merge
sbatch -o L2A34-5M_merge_rrna_removal.out rrna_removal.sh L2A34-5M_merge
sbatch -o L2B34-4M_merge_rrna_removal.out rrna_removal.sh L2B34-4M_merge
sbatch -o L3A23-5M_merge_rrna_removal.out rrna_removal.sh L3A23-5M_merge
sbatch -o L3A56-2F_merge_rrna_removal.out rrna_removal.sh L3A56-2F_merge
sbatch -o L3B24-5F_merge_rrna_removal.out rrna_removal.sh L3B24-5F_merge
sbatch -o L3B910-7M_merge_rrna_removal.out rrna_removal.sh L3B910-7M_merge
sbatch -o MFA22-1M_merge_rrna_removal.out rrna_removal.sh MFA22-1M_merge
sbatch -o MFA22-3F_merge_rrna_removal.out rrna_removal.sh MFA22-3F_merge
sbatch -o MFA88-4M_merge_rrna_removal.out rrna_removal.sh MFA88-4M_merge
sbatch -o MFA88-8F_merge_rrna_removal.out rrna_removal.sh MFA88-8F_merge
sbatch -o MFB22-8M_merge_rrna_removal.out rrna_removal.sh MFB22-8M_merge
sbatch -o MFB88-3M_merge_rrna_removal.out rrna_removal.sh MFB88-3M_merge
sbatch -o SAA23-5F_merge_rrna_removal.out rrna_removal.sh SAA23-5F_merge
sbatch -o SAB34-5M_merge_rrna_removal.out rrna_removal.sh SAB34-5M_merge
sbatch -o SAB57-2M_merge_rrna_removal.out rrna_removal.sh SAB57-2M_merge
