sbatch -o CB12F_adults_rrna_removal.out adults_rrna_removal.sh CB12F
sbatch -o CB12M_adults_rrna_removal.out adults_rrna_removal.sh CB12M
sbatch -o CB78F_adults_rrna_removal.out adults_rrna_removal.sh CB78F
sbatch -o CB78M_adults_rrna_removal.out adults_rrna_removal.sh CB78M
sbatch -o CB910F_adults_rrna_removal.out adults_rrna_removal.sh CB910F
sbatch -o CB910M_adults_rrna_removal.out adults_rrna_removal.sh CB910M
sbatch -o L1A56F_adults_rrna_removal.out adults_rrna_removal.sh L1A56F
sbatch -o L1A56M_adults_rrna_removal.out adults_rrna_removal.sh L1A56M
sbatch -o L1A78F_adults_rrna_removal.out adults_rrna_removal.sh L1A78F
sbatch -o L1A78M_adults_rrna_removal.out adults_rrna_removal.sh L1A78M
sbatch -o L1A910F_adults_rrna_removal.out adults_rrna_removal.sh L1A910F
sbatch -o L1A910M_adults_rrna_removal.out adults_rrna_removal.sh L1A910M
#sbatch -o L1B12F_adults_rrna_removal.out adults_rrna_removal.sh L1B12F
sbatch -o L1B12M_adults_rrna_removal.out adults_rrna_removal.sh L1B12M
sbatch -o L1B67F_adults_rrna_removal.out adults_rrna_removal.sh L1B67F
sbatch -o L1B67M_adults_rrna_removal.out adults_rrna_removal.sh L1B67M
sbatch -o L1B810F_adults_rrna_removal.out adults_rrna_removal.sh L1B810F
sbatch -o L1B810M_adults_rrna_removal.out adults_rrna_removal.sh L1B810M
sbatch -o L2A12F_adults_rrna_removal.out adults_rrna_removal.sh L2A12F
sbatch -o L2A12M_adults_rrna_removal.out adults_rrna_removal.sh L2A12M
sbatch -o L2A34F_adults_rrna_removal.out adults_rrna_removal.sh L2A34F
sbatch -o L2A34M_adults_rrna_removal.out adults_rrna_removal.sh L2A34M
sbatch -o L2A56F_adults_rrna_removal.out adults_rrna_removal.sh L2A56F
sbatch -o L2A56M_adults_rrna_removal.out adults_rrna_removal.sh L2A56M
sbatch -o L2B109F_adults_rrna_removal.out adults_rrna_removal.sh L2B109F
sbatch -o L2B109M_adults_rrna_removal.out adults_rrna_removal.sh L2B109M
sbatch -o L2B12F_adults_rrna_removal.out adults_rrna_removal.sh L2B12F
sbatch -o L2B12M_adults_rrna_removal.out adults_rrna_removal.sh L2B12M
sbatch -o L2B34F_adults_rrna_removal.out adults_rrna_removal.sh L2B34F
sbatch -o L2B34M_adults_rrna_removal.out adults_rrna_removal.sh L2B34M
sbatch -o L3A23F_adults_rrna_removal.out adults_rrna_removal.sh L3A23F
sbatch -o L3A23M_adults_rrna_removal.out adults_rrna_removal.sh L3A23M
sbatch -o L3A56F_adults_rrna_removal.out adults_rrna_removal.sh L3A56F
sbatch -o L3A56M_adults_rrna_removal.out adults_rrna_removal.sh L3A56M
sbatch -o L3A78F_adults_rrna_removal.out adults_rrna_removal.sh L3A78F
sbatch -o L3A78M_adults_rrna_removal.out adults_rrna_removal.sh L3A78M
sbatch -o L3B24F_adults_rrna_removal.out adults_rrna_removal.sh L3B24F
sbatch -o L3B24M_adults_rrna_removal.out adults_rrna_removal.sh L3B24M
sbatch -o L3B78F_adults_rrna_removal.out adults_rrna_removal.sh L3B78F
sbatch -o L3B78M_adults_rrna_removal.out adults_rrna_removal.sh L3B78M
sbatch -o L3B910F_adults_rrna_removal.out adults_rrna_removal.sh L3B910F
sbatch -o L3B910M_adults_rrna_removal.out adults_rrna_removal.sh L3B910M
sbatch -o SAA23F_adults_rrna_removal.out adults_rrna_removal.sh SAA23F
sbatch -o SAA23M_adults_rrna_removal.out adults_rrna_removal.sh SAA23M
sbatch -o SAA45F_adults_rrna_removal.out adults_rrna_removal.sh SAA45F
sbatch -o SAA45M_adults_rrna_removal.out adults_rrna_removal.sh SAA45M
sbatch -o SAA68F_adults_rrna_removal.out adults_rrna_removal.sh SAA68F
sbatch -o SAA68M_adults_rrna_removal.out adults_rrna_removal.sh SAA68M
sbatch -o SAB34F_adults_rrna_removal.out adults_rrna_removal.sh SAB34F
sbatch -o SAB34M_adults_rrna_removal.out adults_rrna_removal.sh SAB34M
sbatch -o SAB57F_adults_rrna_removal.out adults_rrna_removal.sh SAB57F
sbatch -o SAB57M_adults_rrna_removal.out adults_rrna_removal.sh SAB57M
sbatch -o SAB98F_adults_rrna_removal.out adults_rrna_removal.sh SAB98F
sbatch -o SAB98M_adults_rrna_removal.out adults_rrna_removal.sh SAB98M
